#!/bin/bash
# Creates a symlink filename -> md5(contents) for each file specified by the
# given selector. Duplicates are implicitly merged. For example:
#
# $ echo foo > bar
# $ echo foo > bif
# $ md5sum bar
# d3b07384d113edec49eaa6238ad5ff00  bar
# $ hardlink-files-to-hashes './ > b..'
# creating md5(bar) = d3b07384d113edec49eaa6238ad5ff00
# symlinking d3b07384d113edec49eaa6238ad5ff00 to bar
# symlinking d3b07384d113edec49eaa6238ad5ff00 to bif
# $ ls
# bar
# bif
# d3b07384d113edec49eaa6238ad5ff00
# $
#
# Note that this script will not detect permission/owner/attribute differences.

IFS=$'\n'
lines="$(perlquery "$1" .each md5sum)"

for line in $lines; do
  sum=$(echo $line | awk '{print $1}')
  file=$(echo $line | awk '{print $2}')

  if [[ ! -L "$file" ]]; then
    [[ -e sum ]] || (echo "creating md5($file) = $sum" && cp "$file" $sum)
    rm "$file" && echo "symlinking $sum to $file" && ln -rs $sum "$file"
  else
    echo "skipping symlink $file"
  fi
done
